name: Deploy Firebase Hosting

# 觸發條件：push 到 main 分支或特定分支
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 取得程式碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 安裝 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ 安裝相依套件
      - name: Install dependencies
        run: npm ci

      # 4️⃣ 建置專案（例如 React/Next.js）
      - name: Build project
        run: npm run build

      # 5️⃣ 部署到 Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"                # 自動提供的 token
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"  # 你的 Service Account JSON
          projectId: "react-app-34d4b"                           # Firebase 專案 ID
